apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: jenkins-test   # Ensure the service is in the correct namespace
spec:
  selector:
    app: python-app          # Ensure this matches the pod labels (if labels are added)
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80 on the service
    targetPort: 80           # Forward traffic to port 80 on the container
  type: ClusterIP            # This can be changed to LoadBalancer or NodePort if needed
